// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/viniciusataide/velozient-challenge-go/domain"
	"github.com/viniciusataide/velozient-challenge-go/passwordcards"
	"github.com/viniciusataide/velozient-challenge-go/server"
	"github.com/viniciusataide/velozient-challenge-go/utils"
)

import (
	_ "github.com/viniciusataide/velozient-challenge-go/docs"
)

// Injectors from wire.go:

func bootstrap(app *fiber.App) *passwordcards.Controller {
	v := domain.ProvideCards()
	config := server.ProvideConfig()
	crypto := utils.ProvideCrypto(config)
	repository := passwordcards.ProvideRepository(v, crypto)
	service := passwordcards.ProvideService(repository)
	serverServer := server.ProvideServer(app, config)
	controller := passwordcards.ProvideController(service, serverServer)
	return controller
}

func bootstrapTest(app *fiber.App) *passwordcards.Controller {
	config := server.ProvideConfig()
	crypto := utils.ProvideCrypto(config)
	v := utils.ProvideTestCards(crypto)
	repository := passwordcards.ProvideRepository(v, crypto)
	service := passwordcards.ProvideService(repository)
	serverServer := server.ProvideServer(app, config)
	controller := passwordcards.ProvideController(service, serverServer)
	return controller
}
